config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :bookings
  #get 'pages/home'
  root 'pages#home'
  #get 'pages/about'
  get '/about' => 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
    #validate before writing to table in database
    validates :name, :presence => true, length: {minimum: 3, message: "must have 3+ letters"}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def admin?  
        if current_user && current_user.admin?
            return admin?
        end
    end

    #putting this method here makes it available across whole application 
    def ensure_admin 
        unless current_user && current_user.admin? 
            respond_to do |format| 
                format.html { redirect_to root_path, notice: 'Please contact the administrator to complete this action.' } 
                format.json { head :no_content } 
            end 
        end
    end 
end

app/controllers/bookings_controller.rb
require 'booking_decorator'
require 'my_logger'

class BookingsController < ApplicationController
  #original: before_action :set_booking, only: %i[ show edit update destroy ]
  before_action :set_booking, only: %i[ show ] #only show bookings before signing in
  before_action :user_signed_in?, only:[:edit, :create, :update, :destroy]
  #before_action :authenticate_user!
  #before_action :admin?, only: [:destroy]
  
  # GET /bookings or /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    @booking = Booking.new(booking_params)
    #@booking = Booking.new()
    #@booking.name = params [:booking][:name]
    #@booking.date = params [:booking][:date]
    #@booking.time = params [:booking][:time]
    #@booking.size = params [:booking][:size]
    #@booking.note = params [:booking][:note]

    #checkedBooking = BasicBooking.new(booking.size)

    #checkedBooking = DecoratedBooking.new(checkedBooking)

    #@booking.note = @booking.note + " " + checkedBooking.size
    
    logger = MyLogger.instance
    logger.logInfo("New Booking Created: " +@booking.name)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully created." }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy
    
    logger = MyLogger.instance
    logger.logInfo("Booking Destroyed: " +@booking.name)

    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:name, :date, :time, :size, :note)
    end

end

app/controllers/pages_controller.rb
require 'httparty'

class PagesController < ApplicationController
  def home
    response = HTTParty.get('https://v2.jokeapi.dev/joke/Programming?blacklistFlags=racist,sexist,explicit')
    @random = JSON.parse(response.body)
    @randomsetup = @random['setup']
    @randomdeliver = @random['delivery']
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">
  <p>
    <strong>Name:</strong>
    <%= booking.name %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= booking.date %>
  </p>

  <p>
    <strong>Time:</strong>
    <%= booking.time %>
  </p>

  <p>
    <strong>Size:</strong>
    <%= booking.size %>
  </p>

  <p>
    <strong>Note:</strong>
    <%= booking.note %>
  </p>

</div>

app/views/bookings/_form.html.erb
<%= form_with(model: booking) do |form| %>
  <% if booking.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :time, style: "display: block" %>
    <%= form.time_field :time %>
  </div>

  <div>
    <%= form.label :size, style: "display: block" %>
    <%= form.number_field :size %>
  </div>

  <div>
    <%= form.label :note, style: "display: block" %>
    <%= form.text_field :note %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Show this booking", @booking %> |
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bookings</h1>

<div id="bookings">
  <% @bookings.each do |booking| %>
    <%= render booking %>
    <p>
      <%= link_to "Show this booking", booking %>
    </p>
  <% end %>
</div>

<%= link_to "New booking", new_booking_path %>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @booking %>

<div>
  <%= link_to "Edit this booking", edit_booking_path(@booking) %> |
  <%= link_to "Back to bookings", bookings_path %>

  <%= button_to "Destroy this booking", @booking, method: :delete %>
</div>

app/views/layouts/_nav.html.erb
<p>nav bar</p>
    <%= link_to "home", root_path %> &nbsp;
        <% if !user_signed_in? %> 
            <%= link_to "Login", new_user_session_path %> &nbsp; 
        <% else %> 
            <%= current_user.email %> &nbsp; 
            <%= link_to "Sign out", destroy_user_session_path, 'data-turbo-method': :delete %> &nbsp; 
        <% end %> 
    <%= link_to "All Bookings", bookings_path %> &nbsp; 
    <%= link_to "About Page", about_path %> &nbsp; 
    <% if current_user.try(:admin?) %> 
    <!-- only visible to admin user --> 
    <span> admin </span> 
<% end %> 
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookings</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p> &nbsp;
<p>This is a booking app for Mario's restaurant</p> &nbsp;
<p>123 Rails Road, Dublin 1</p>&nbsp;
<p>8201234</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<p>Programmer joke Q: <%= @random['setup'].inspect %></p> 
<p>A: <%= @random['delivery'].inspect %> &nbsp;</p>
<%#= icon('fa-regular', 'face-laugh-squint')%>